### ISSUE TITLE
Remote infomation flags (i.e. `-x`) cannot be filtered by console

### ISSUE THREAD

**Issue by GeraldNDA** [conserver/conserver#12]
Informational flags: `-x`, `-w`, `-u`, `-i` do not work on a remote master when a `console` to filter by is specified.

`console -x` works as expected:
```
> console -x
 slot0                    on /dev/cuaU1@localhost             at 115200n
 devpowerctl              on /dev/cuaU0@localhost             at 115200n   
```
however `console -x <console>` gives:
```
> console -x slot0
unknown command  
```
This is not an issue on the local conserver.

**Comment by GeraldNDA** [comment]
For the machine with the remote master (aka serialuser). This is the machine where the bug occurs. Here is the config:
```
default * {
	master remoteserial;
	rw *;
}

default serial {
	type device;
	device /dev/cuaU?;
	devicesubst ?=Pd;

	baud 115200;
	parity none;

	# For the benefit of expect scripts
	logfile /tmp/&.boot.log;
	motd "[connected]";
}

default device serial {
	include serial;
	portbase 1;
}

console devpowerctl { include serial; port 0; }
console slot0 {
 	aliases pinea64;
	include device serial; port 0;
}
```

For the local machine which provides the serial ports (aka remoteserial), here is the config:
```

```default * {
	master localhost;
	rw *;
}

access * {
	trusted serialuser;
	trusted localhost;
}

default serial {
	type device;
	device /dev/cuaU?;
	devicesubst ?=Pd;

	baud 115200;
	parity none;

	# For the benefit of expect scripts
	logfile /tmp/&.boot.log;
	motd "[connected]";
}

default device serial {
	include serial;
	portbase 1;
}

console devpowerctl { include serial; port 0; }
console slot0 {
 	aliases pinea64;
	include device serial; port 0;
}
```

**Comment by GeraldNDA** [comment]
Additionally, you can use informational flags if you don't explicitly state the master server.
i.e.
```
> console -M remoteserial -x slot0
 slot0                    on /dev/cuaU1@localhost             at 115200n   
```

**Comment by conserver** [comment]
Well, I've tried various setups to replicate this issue and no matter what I try, I can't get it to happen.  I do believe I know what's going on, and it all has to do with your use of `master localhost`, but even though I can imagine how this would occur, I failed making it happen.  To help confirm, could you send me the output of `console -x slot0 -DD` with the failure case?  I believe it all has to do with the determination of the master server and somehow your environment is sending the client back to the local instance versus going remote.

Even without the debug output, you could just change `master localhost` to `master remoteserial` and see if that fixes it.  In the simplest case (per your posted configs), you don't actually need a `conserver.cf` on `serialuser`.  All it's doing is talking to `remoteserial` so just make sure the default master server maps to `remoteserial` and run the client.  If you have serial ports on multiple machines (and so need to run `conserver` on each), you put the same config file on each host and just make sure the consoles have the right `master` config element.

Anyway, hopefully that helps - lemme know!

**Comment by GeraldNDA** [comment]
1. Changing `master localhost` to `master remoteserial` seemed to have no effect.
2. Question: If I don't use a `conserver.cf`on `serialuser`, I'd have to specify the `-M` option whenever I use a console. Correct?
3. Debug output: [results.txt](https://github.com/conserver/conserver/files/2980821/results.txt) (hostnames were modified to match configs above)

**Comment by conserver** [comment]
Oh, what version of conserver are you running?  I do see a misbehaving client here in the logs, but still cannot replicate it.  I thought I had seen a recent version specified somewhere in your messages, but now can't find it, so I have to ask.  ;-)

**Comment by GeraldNDA** [comment]
Here's my version info:
```
console: conserver.com version 8.2.2
console: default initial master server `localhost'
console: default port referenced as `782'
console: default escape sequence `^Ec'
console: default site-wide configuration in `/usr/local/etc/console.cf'
console: default per-user configuration in `$HOME/.consolerc'
console: options: libwrap, openssl
console: openssl version: OpenSSL 1.1.1a-freebsd  20 Nov 2018
console: built with `./configure --with-master=localhost --with-port=782 --with-pam --with-libwrap --with-openssl --without-gssapi --without-striprealm --without-uds --prefix=/usr/local --localstatedir=/var --mandir=/usr/local/man --infodir=/usr/local/share/info/ --build=amd64-portbld-freebsd12.0'
```

It is the same on both computers. I believe I tried 8.2.3 as well, with similar issues.

**Comment by GeraldNDA** [comment]
I tried 8.2.3 with no luck. I also turned on debugging info and noted that "examine slot1" was indeed received on that end so I'm not sure what's up. I can include those debug logs as well if that'll help.

**Comment by conserver** [comment]
Good news, I was finally able to reproduce your problem (and feeling a bit sad that I screwed up my setup and failed before).  I certainly see the issue now...just gotta come up with a way to make it work right.  Thanks for putting in all the details!  Hopefully a solution will be relatively soon.

**Comment by conserver** [comment]
Forgot to answer a question of yours:

Question: If I don't use a conserver.cfon serialuser, I'd have to specify the -M option whenever I use a console. Correct?

True, unless you build conserver with a master server name that you can make point at three right place. Usually folks have an alias in DNS for “console” or some such so things just reach out directly. 

Lemme know if the patch doesn’t work for you - fixed my setup!

**Comment by GeraldNDA** [comment]
The patch does fix the issue. Thanks!

Also thanks for the tip. I'm not sure if rebuilding conserver works in my case, but I using a DNS alias or /etc/hosts instead might work for me.
