### ISSUE TITLE
Missing configure script

### ISSUE THREAD

**Issue by hvdkooij** [conserver/conserver#34]
The quick install instructions metion I should start with ./configure
But that command is not yet present. 

I have been away from installing from sources too long it seems so I need some guidance. What should be the next step after the git clone command?

**Comment by hvdkooij** [comment]
Tried automake:

#  automake
configure.ac: error: no proper invocation of AM_INIT_AUTOMAKE was found.
configure.ac: You should verify that configure.ac invokes AM_INIT_AUTOMAKE,
configure.ac: that aclocal.m4 is present in the top-level directory,
configure.ac: and that aclocal.m4 was recently regenerated (using aclocal)
configure.ac:360: error: required file './config.guess' not found
configure.ac:360:   'automake --add-missing' can install 'config.guess'
configure.ac:360: error: required file './config.sub' not found
configure.ac:360:   'automake --add-missing' can install 'config.sub'
automake: error: no 'Makefile.am' found for any configure output

So that does not seem to work. At least not on my PI.

**Comment by hvdkooij** [comment]
It seems this works better:
```
git clone ....
autoconf
./configure 
```

But the it fails on:
`config.status: error: cannot find input file: `config.h.in'`

**Comment by conserver** [comment]
The code isn't directly configurable from the git repository.  I suggest you download the latest release bundle (https://github.com/conserver/conserver/releases), which has all the autoconf steps performed and is at a release point.  If you really want to build from a clone, I suggest looking at/watching the .cirrus.yml file, as that is used to do automated builds.

**Comment by conserver** [comment]
Oh, and I forgot to mention https://github.com/conserver/conserver/tree/master/package.  That might be of some service.
