### ISSUE TITLE
Small error when running "./package/make-and-stage-release local"

### ISSUE THREAD

**Issue by marcoroe** [conserver/conserver#35]
When running the command "./package/make-and-stage-release local" on a Centos 7 machine an error interrupts the execution of the script:
"sed: can't read : No such file or directory"

By sed manual, when using the " -i[SUFFIX] " option there should be no space between the i and the suffix string. Doing so on lines 30 and 31 of the script solves the issue for me.

I think it may be useful to correct it, if it does not cause problems with other systems.

**Comment by emaste** [comment]
For reference BSD sed requires a suffix with `-i`, and it can either immediately follow or have a space between.
