### ISSUE TITLE
clang `-Wstring-plus-int` warning

### ISSUE THREAD

**Issue by emaste** [conserver/conserver#6]
Building on FreeBSD I see:
```
master.c:566:18: warning: adding 'int' to a string does not append to the string [-Wstring-plus-int]
                                      ":@%s" + iSep, pRC->rhost);
                                      ~~~~~~~^~~~~~
master.c:566:18: note: use array indexing to silence this warning
                                      ":@%s" + iSep, pRC->rhost);
                                             ^
                                      &      [     ]
```

Clang's suggestion is `":@%s" + iSep` -> `&":@%s"[iSep]`. I'm not entirely sure this is more clear; perhaps this warning ought to be disabled.

**Comment by conserver** [comment]
Yeah, I’m not sure either. I need to really test things across a few environments to see if one is better than the other. I’m sure there are many more warnings and such to deal with too...

**Comment by robohack** [comment]
I would say Clang's -Wstring-plus-int warning is entirely unnecessary -- it's probably meant for C++ programmers who don't understand C, or some such.
